os: windows
language: shell
branches:
  only:
  - master
script:
- powershell -command \".\ci.ps1 -deploy 1\"
after_script:
- choco apikey --key $CHOCOAPIKEY --source https://push.chocolatey.org/
- choco push
