os: windows
language: shell
branches:
  only:
  - master
script:
- choco pack \"$((Get-ChildItem .\\*\\*.nuspec).FullName)\"
after_script:
- choco apikey --key $CHOCOAPIKEY --source https://push.chocolatey.org/
- choco push
